# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-21 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20190121_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
