# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-21 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_auto_20190121_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='date',
            new_name='when',
        ),
    ]
