# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-21 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_auto_20190121_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='when',
        ),
        migrations.AddField(
            model_name='rate',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
